---
title: "original_demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{original_demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(convplot)


# Sample data for ElPaCo eScience project
# MD 202302



# Packages & functions ----------------------------------------------------

# Packages
list.of.packages <- c("tidyverse","ggthemes","ggrepel","knitr","data.table","viridis","ggridges","cowplot")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
lapply(list.of.packages, require, character.only=T)

# Load functions
source("helper-functions.R")


# Load data ---------------------------------------------------------------

# subset of six languages and 5 source files per language
# originates in: elpaco-lingdiv-branch-escience.R
d <- read_csv("data/d_sample.csv")

# metadata of corpora included in sample
d.metadata <- read_csv("data/d_sample_metadata.csv")

# tokenized data (generated using white space tokenizer without further assumptions)
d.tokens <- read_csv("data/d_sample_tokens.csv")


# Quick demo of existing code ---------------------------------------------

# Warts and all!

# inspect_corpus(): a quick quantitative + qualitative peek at a corpus
# Liesenfeld & Dingemanse LREC

inspect_corpus(lang="dutch")
inspect_corpus(lang="siwu")

# convplot(): function to display time-aligned 'piano roll' style plot of a conversation
# Dingemanse & Liesenfeld ACL

convplot(n=10,content=T,dyads=T)

```
