# This test suite checks that the plots generated by this package make sense.
# It uses testthat::expect_snapshot_file. This is how it works:
#
# The first time expect_snapshot_file is run, it creates a reference image. An
# expert validates it manually, and it gets stored.
#
# Every other time expect_snapshot_file is run, it compares the output with the
# reference image. If the new and the reference image are identical, the test
# passes. Otherwise, it fails.
#
# When fail, testthat provides some useful tools to visually compare the differences
# between new and reference image. They are clickable from the test menu.

# Load the test data
testdata <- ifadv::ifadv

#' Auxiliary decorator
#'
#' This decorator extends the functionality of any plotting function with:
#'
#' 1. Saving the plot to a png file
#' 2. Returning the path
#'
#' This is required by testthat::expect_snapshot_file to work with graphics.
#' More information at:
#'
#' https://indrajeetpatil.github.io/intro-to-snapshot-testing/#/writing-test
#'
#' @param plot_function The plotting function to be tested
#' @param path The output filename
#'
#' @return The plot_function, decorated with save to path functionality
#'
#' @examples
#' \dontrun{
#' # Consider these lines
#' plot_quality(data) # Plots the data
#'
#' path <- "~/Desktop/myplot.png"
#' plot_quality_and_save <- with_save(plot_quality, path)
#' plot_quality_and_save(data) # Plots the data, saves it to the given path, and returns the string "~/Desktop/myplot.png"
#' }
with_save <- function(plot_function, path) {

  force(plot_function) # Evaluate now and avoid problems with lazy evaluation

  #' Decorated ploting function
  #'
  #' Original plotting functionality + save to path
  #'
  #' @param ... Any parameters for the original plotting function
  #'
  #' @return The output filename
  decorated <- function(...) {
    p <- plot_function(...) # Plot as usual ...
    ggplot2::ggsave(path) # ... and save

    return(path)
  }

  return(decorated)
}

test_that("Plot quality", {
  path <- "plot_quality.png"
  plot_and_save <- with_save(plot_quality, path)

  expect_snapshot_file(
    plot_and_save(testdata),
    path
  )

  on.exit(file.remove(path)) # Clean afterwards
})

test_that("Plot density", {
  path <- "plot_density.png"
  plot_and_save <- with_save(plot_density, path)

  expect_snapshot_file(
    plot_and_save(testdata, colname="freq"),
    path
  )

  on.exit(file.remove(path)) # Clean afterwards
})

test_that("Plot scatter", {
  path <- "plot_scatter.png"
  plot_and_save <- with_save(plot_scatter, path)

  expect_snapshot_file(
    plot_and_save(testdata, colname_x="begin", colname_y="end"),
    path
  )

  on.exit(file.remove(path)) # Clean afterwards
})
